"""Build the paper AeroGraph Reasoner table from the latest valid evaluation."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


DEFAULT_CANDIDATES = [
    "outputs/reasoning/aerograph_prompt_pack_eval_manual_web/manifest.json",
    "outputs/reasoning/aerograph_prompt_pack_eval_chatgpt_web/manifest.json",
    "outputs/reasoning/aerograph_prompt_pack_eval_openai/manifest.json",
    "outputs/reasoning/aerograph_prompt_pack_eval_command/manifest.json",
    "outputs/reasoning/aerograph_prompt_pack_eval_manual/manifest.json",
]


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}


def is_complete_nonmock(manifest: dict[str, Any]) -> bool:
    if not manifest:
        return False
    if manifest.get("paper_claim_allowed") is False:
        return False
    provider = str(manifest.get("provider") or "").lower()
    # Internal/manual review manifests are useful paper-visible candidates, but
    # they should not be promoted as the final external-provider benchmark.
    if "assisted" in provider or "manual review" in provider or "review candidate" in provider:
        return False
    if manifest.get("non_mock_outputs_ready") is not True:
        return False
    summary = manifest.get("summary", {}) or {}
    total = int(summary.get("total", 0) or 0)
    nonmock = int(manifest.get("non_mock_output_count", 0) or 0)
    valid_nonmock = int(manifest.get("valid_non_mock_output_count", 0) or 0)
    return total > 0 and nonmock == total and valid_nonmock == total


def find_best_manifest(candidates: list[Path]) -> tuple[Path | None, dict[str, Any]]:
    for path in candidates:
        manifest = read_json(path)
        if is_complete_nonmock(manifest):
            return path, manifest
    return None, {}


def is_reviewed_candidate(manifest: dict[str, Any]) -> bool:
    if not manifest:
        return False
    provider = str(manifest.get("provider") or "").lower()
    summary = manifest.get("summary", {}) or {}
    total = int(summary.get("total", 0) or 0)
    valid = int(manifest.get("valid_non_mock_output_count", 0) or 0)
    return total > 0 and valid == total and (
        "assisted" in provider or "manual review" in provider or "review candidate" in provider
    )


def find_reviewed_candidate(candidates: list[Path]) -> tuple[Path | None, dict[str, Any]]:
    for path in candidates:
        manifest = read_json(path)
        if is_reviewed_candidate(manifest):
            return path, manifest
    return None, {}


def pending_table(prompt_count: int, validation_scope: str) -> str:
    safe_scope = tex_escape(validation_scope)
    return "\n".join(
        [
            "% Reserved slot for the final external-provider AeroGraph Reasoner table.",
            "% Auto-generated by scripts/build_aerograph_reasoner_table.py.",
            r"\begin{tabular}{lrrrrl}",
            r"\toprule",
            r"Reasoner & Prompts & Verified & Uncertain & Rejected & Validation scope \\",
            r"\midrule",
            f"AeroGraph Reasoner & {prompt_count} & -- & -- & -- & {safe_scope} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def complete_table(manifest: dict[str, Any], manifest_path: Path) -> str:
    summary = manifest.get("summary", {}) or {}
    decisions = summary.get("by_decision", {}) or {}
    total = int(summary.get("total", 0) or 0)
    verified = int(decisions.get("verified", 0) or 0)
    uncertain = int(decisions.get("uncertain", 0) or 0)
    rejected = int(decisions.get("rejected", 0) or 0)
    mismatches = int(summary.get("class_mismatch_count", 0) or 0)
    provider = "AeroGraph Reasoner"
    validation_scope = tex_escape(f"External validation complete; class-check mismatches {mismatches}")
    return "\n".join(
        [
            "% Final external-provider AeroGraph Reasoner table.",
            "% Auto-generated by scripts/build_aerograph_reasoner_table.py.",
            r"\begin{tabular}{lrrrrl}",
            r"\toprule",
            r"Reasoner & Prompts & Verified & Uncertain & Rejected & Validation scope \\",
            r"\midrule",
            f"{provider} & {total} & {verified} & {uncertain} & {rejected} & {validation_scope} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )


def candidate_table(manifest: dict[str, Any], manifest_path: Path) -> str:
    summary = manifest.get("summary", {}) or {}
    total = int(summary.get("total", 0) or 0)
    validation_scope = "External-provider replication to be imported"
    return "\n".join(
        [
            "% Reviewed candidate table reserved for external-provider replication.",
            "% Auto-generated by scripts/build_aerograph_reasoner_table.py.",
            r"\begin{tabular}{lrrrrl}",
            r"\toprule",
            r"Reasoner & Prompts & Verified & Uncertain & Rejected & Validation scope \\",
            r"\midrule",
            f"AeroGraph Reasoner & {total} & -- & -- & -- & {validation_scope} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ]
    )


def prompt_count_from_pack(path: Path) -> int:
    if not path.exists():
        return 0
    return sum(1 for line in path.read_text(encoding="utf-8").splitlines() if line.strip())


def build(args: argparse.Namespace) -> dict[str, Any]:
    candidates = [Path(item) for item in (args.candidates or DEFAULT_CANDIDATES)]
    selected_path, selected = find_best_manifest(candidates)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if selected_path and selected:
        out_path.write_text(complete_table(selected, selected_path), encoding="utf-8")
        status = "aerograph_reasoner_table_complete"
        reviewed_path, reviewed = None, {}
    else:
        reviewed_path, reviewed = find_reviewed_candidate(candidates)
        if reviewed_path and reviewed:
            out_path.write_text(candidate_table(reviewed, reviewed_path), encoding="utf-8")
            status = "aerograph_reasoner_table_candidate_external_pending"
        else:
            prompt_count = prompt_count_from_pack(Path(args.prompt_pack))
            latest_state = "External-provider run to be imported"
            seen = [read_json(path) for path in candidates if path.exists()]
            if seen:
                latest_state = "Complete external-provider run to be imported"
            out_path.write_text(pending_table(prompt_count, latest_state), encoding="utf-8")
            status = "aerograph_reasoner_table_pending"

    manifest = {
        "status": status,
        "out": str(out_path),
        "selected_manifest": str(selected_path) if selected_path else "",
        "reviewed_candidate_manifest": str(reviewed_path) if reviewed_path else "",
        "candidate_manifests": [str(path) for path in candidates],
        "non_mock_outputs_ready": bool(selected_path),
        "external_provider_replication_ready": bool(selected_path),
        "reviewed_candidate_ready": bool(reviewed_path),
    }
    manifest_path = Path(args.manifest_out)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Build paper AeroGraph reasoner table.")
    parser.add_argument("--out", default="paper/tables/aerograph_reasoner_results_placeholder.tex")
    parser.add_argument("--manifest-out", default="outputs/reports/live/aerograph_reasoner_table_manifest.json")
    parser.add_argument("--prompt-pack", default="outputs/reports/live/aerograph_prompt_pack/aerograph_prompts_all.jsonl")
    parser.add_argument("--candidates", nargs="*", default=[])
    args = parser.parse_args()
    print(json.dumps(build(args), indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
