"""Build MarineCity closed-loop re-observation update artifacts.

The script keeps paper files untouched. It reads the current 78-token
viewer160 cross-view graph as the before state, inserts matching detector
tokens from the later real-Cesium session recapture as targeted re-observation
evidence, and writes review-response figures/tables under outputs/reports.

This validates the graph update contract using real-Cesium detector tokens.
The re-observation tokens may come from saved session recaptures or from fresh
Isaac/Cesium camera poses generated by the targeted re-observation plan.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import sys
import textwrap
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".cache/matplotlib"))
os.environ.setdefault("XDG_CACHE_HOME", str(ROOT / ".cache"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from evidence import EvidenceToken, load_tokens_jsonl
from scripts.build_marinecity_crossview_evidence_graph import (
    class_name,
    distance_xy,
    project_token,
    route_action,
    scenario_id,
    short_scenario,
)


DEFAULT_BASE_GRAPH = ROOT / "outputs/graphs/marinecity_viewer160_crossview_evidence_graph"
DEFAULT_REOBS_TOKENS = ROOT / "outputs/evidence/marinecity_real_capture_detector_smoke/evidence_tokens.jsonl"
DEFAULT_OUT = ROOT / "outputs/reports/live/closed_loop_reobservation_20260703"
UAV_IDS = ["uav_01", "uav_02", "uav_03"]


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


def token_key(token: EvidenceToken) -> str:
    return f"{short_scenario(scenario_id(token))}:{token.uav_id}:{class_name(token)}:{token.token_id}"


def load_base_tokens(graph_dir: Path) -> dict[str, EvidenceToken]:
    summary = read_json(graph_dir / "summary.json")
    token_path = Path(summary["source_tokens"])
    tokens = load_tokens_jsonl(token_path)
    return {token.token_id: token for token in tokens}


def token_projection(token: EvidenceToken, hfov_deg: float, ground_z: float) -> dict[str, Any]:
    return project_token(token, hfov_deg=hfov_deg, ground_z=ground_z)


def find_reobserve_candidate(
    hypothesis: dict[str, Any],
    reobserve_tokens: list[EvidenceToken],
    projections: dict[str, dict[str, Any]],
    *,
    max_distance: float,
    min_confidence: float,
) -> tuple[EvidenceToken | None, float | None, list[dict[str, Any]]]:
    scenario = hypothesis["scenario_short"]
    cls = hypothesis["class_name"]
    missing = set(hypothesis.get("missing_uav_ids", []))
    center = hypothesis["center_scene_units"]
    candidates: list[tuple[float, EvidenceToken]] = []
    considered: list[dict[str, Any]] = []
    for token in reobserve_tokens:
        if float(token.confidence) < min_confidence:
            continue
        token_hypothesis = str(token.metadata.get("hypothesis_id") or "")
        token_scenario = str(token.metadata.get("scenario_short") or short_scenario(scenario_id(token)))
        if token_hypothesis and token_hypothesis != hypothesis["hypothesis_id"]:
            continue
        if token_hypothesis and token_hypothesis == hypothesis["hypothesis_id"]:
            if class_name(token) == cls and token.uav_id in missing:
                dist = distance_xy(projections[token.token_id]["association_point"], center)
                candidates.append((dist, token))
                considered.append(
                    {
                        "token_id": token.token_id,
                        "uav_id": token.uav_id,
                        "class_name": class_name(token),
                        "confidence": float(token.confidence),
                        "uncertainty": float(token.uncertainty),
                        "distance_xy": dist,
                        "match_reason": "hypothesis_id",
                    }
                )
            continue
        if short_scenario(scenario_id(token)) != scenario:
            if token_scenario != scenario:
                continue
        if token_scenario != scenario:
            continue
        if class_name(token) != cls:
            continue
        if token.uav_id not in missing:
            continue
        dist = distance_xy(projections[token.token_id]["association_point"], center)
        candidates.append((dist, token))
        considered.append(
            {
                "token_id": token.token_id,
                "uav_id": token.uav_id,
                "class_name": class_name(token),
                "confidence": float(token.confidence),
                "uncertainty": float(token.uncertainty),
                "distance_xy": dist,
            }
        )
    candidates.sort(key=lambda item: item[0])
    if not candidates:
        return None, None, considered
    distance, token = candidates[0]
    if distance > max_distance:
        return None, distance, considered
    return token, distance, considered


def after_state(
    hypothesis: dict[str, Any],
    token: EvidenceToken | None,
    *,
    support_gain: float,
    confidence_gain_weight: float,
    max_confidence_gain: float,
) -> dict[str, Any]:
    before_views = set(hypothesis.get("uav_ids", []))
    before_action = hypothesis["recommended_action"]
    before_ambiguity = float(hypothesis["ambiguity_score"])
    before_conf = float(hypothesis.get("mean_confidence", 0.0))
    before_unc = float(hypothesis.get("mean_uncertainty", before_ambiguity))
    before_tokens = int(hypothesis.get("token_count", 1))

    if token is None:
        return {
            "after_view_count": int(hypothesis["view_count"]),
            "after_uav_ids": sorted(before_views),
            "after_token_count": before_tokens,
            "after_mean_confidence": before_conf,
            "after_mean_uncertainty": before_unc,
            "after_raw_ambiguity": before_ambiguity,
            "after_closed_loop_ambiguity": before_ambiguity,
            "after_action": before_action,
            "support_gain_applied": 0.0,
            "confidence_gain_applied": 0.0,
            "resolved": False,
            "resolution_status": "unresolved_no_matching_reobservation_token",
        }

    after_views = set(before_views)
    after_views.add(token.uav_id)
    after_tokens = before_tokens + 1
    token_conf = float(token.confidence)
    token_unc = float(token.uncertainty)
    after_conf = (before_conf * before_tokens + token_conf) / after_tokens
    after_unc = (before_unc * before_tokens + token_unc) / after_tokens

    # Raw recomputation keeps the detector uncertainty dominant. The closed-loop
    # score additionally removes the missing-evidence surcharge once the
    # requested UAV returns a same-class token, which is the actual closed-loop
    # contract under review.
    raw = clamp(after_unc)
    conf_gain = min(max_confidence_gain, max(0.0, token_conf - before_conf) * confidence_gain_weight)
    closed_loop = clamp(raw - support_gain - conf_gain)
    action = route_action(
        view_count=len(after_views),
        ambiguity=closed_loop,
        mean_confidence=after_conf,
        projection_valid_ratio=1.0,
    )
    resolved = before_action == "targeted_reobserve" and action != "targeted_reobserve"
    status = "resolved_to_" + action if resolved else "unresolved_still_ambiguous"
    return {
        "after_view_count": len(after_views),
        "after_uav_ids": sorted(after_views),
        "after_token_count": after_tokens,
        "after_mean_confidence": after_conf,
        "after_mean_uncertainty": after_unc,
        "after_raw_ambiguity": raw,
        "after_closed_loop_ambiguity": closed_loop,
        "after_action": action,
        "support_gain_applied": support_gain,
        "confidence_gain_applied": conf_gain,
        "resolved": resolved,
        "resolution_status": status,
    }


def font(size: int, bold: bool = False) -> ImageFont.ImageFont:
    names = ["DejaVuSans-Bold.ttf", "DejaVuSans.ttf"] if bold else ["DejaVuSans.ttf"]
    for name in names:
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


FONT_TITLE = font(34, True)
FONT_H = font(22, True)
FONT_BODY = font(17)
FONT_SMALL = font(14)


def fit_image(path: Path | None, size: tuple[int, int]) -> Image.Image:
    if not path or not path.exists():
        canvas = Image.new("RGB", size, "#f8fafc")
        draw = ImageDraw.Draw(canvas)
        draw.rectangle([0, 0, size[0] - 1, size[1] - 1], outline="#cbd5e1", width=2)
        draw.text((18, size[1] // 2 - 10), "missing image", fill="#b91c1c", font=FONT_SMALL)
        return canvas
    image = Image.open(path).convert("RGB")
    image.thumbnail(size, Image.Resampling.LANCZOS)
    canvas = Image.new("RGB", size, "#ffffff")
    canvas.paste(image, ((size[0] - image.width) // 2, (size[1] - image.height) // 2))
    return canvas


def token_image_with_box(token: EvidenceToken | None, size: tuple[int, int]) -> Image.Image:
    if token is None:
        return fit_image(None, size)
    image_path = Path(str(token.metadata.get("image_path", "")))
    if not image_path.exists():
        return fit_image(None, size)
    image = Image.open(image_path).convert("RGB")
    original = image.size
    image.thumbnail(size, Image.Resampling.LANCZOS)
    scale_x = image.width / max(1, original[0])
    scale_y = image.height / max(1, original[1])
    canvas = Image.new("RGB", size, "#ffffff")
    x0 = (size[0] - image.width) // 2
    y0 = (size[1] - image.height) // 2
    canvas.paste(image, (x0, y0))
    draw = ImageDraw.Draw(canvas)
    bx, by, bw, bh = [float(v) for v in token.bbox_2d[:4]]
    box = [
        x0 + bx * scale_x,
        y0 + by * scale_y,
        x0 + (bx + bw) * scale_x,
        y0 + (by + bh) * scale_y,
    ]
    draw.rectangle(box, outline="#ef4444", width=4)
    draw.text((box[0], max(0, box[1] - 22)), f"{class_name(token)} {float(token.confidence):.2f}", fill="#ef4444", font=FONT_SMALL)
    return canvas


def crop_for_token(token: EvidenceToken | None) -> Path | None:
    if token is None:
        return None
    crop = token.metadata.get("crop_path")
    if crop:
        path = Path(str(crop))
        if not path.is_absolute():
            path = ROOT / path
        return path
    return None


def wrap(draw: ImageDraw.ImageDraw, text: str, xy: tuple[int, int], width: int, line_height: int, fill: str = "#0f172a") -> int:
    x, y = xy
    for para in text.splitlines():
        for line in textwrap.wrap(para, width=width) or [""]:
            draw.text((x, y), line, fill=fill, font=FONT_BODY)
            y += line_height
    return y


def draw_card(draw: ImageDraw.ImageDraw, box: tuple[int, int, int, int], title: str, body: str, accent: str) -> None:
    draw.rounded_rectangle(box, radius=8, fill="#ffffff", outline=accent, width=3)
    x0, y0, x1, _ = box
    draw.rectangle([x0, y0, x1, y0 + 40], fill=accent)
    draw.text((x0 + 14, y0 + 8), title, fill="white", font=FONT_H)
    wrap(draw, body, (x0 + 14, y0 + 58), 48, 24)


def build_panel(row: dict[str, Any], base_token: EvidenceToken | None, reobs_token: EvidenceToken | None, out_path: Path) -> None:
    canvas = Image.new("RGB", (1800, 1120), "#f8fafc")
    draw = ImageDraw.Draw(canvas)
    draw.rectangle([0, 0, 1800, 82], fill="#0f172a")
    title = f"Closed-loop re-observation: {row['hypothesis_id']} ({row['scenario_short']}, {row['class_name']})"
    draw.text((32, 22), title, fill="white", font=FONT_TITLE)

    before_img = token_image_with_box(base_token, (520, 300))
    reobs_img = token_image_with_box(reobs_token, (520, 300))
    before_crop = fit_image(crop_for_token(base_token), (260, 220))
    reobs_crop = fit_image(crop_for_token(reobs_token), (260, 220))

    canvas.paste(before_img, (40, 130))
    canvas.paste(reobs_img, (640, 130))
    canvas.paste(before_crop, (1240, 130))
    canvas.paste(reobs_crop, (1510, 130))
    draw.text((40, 102), "Before supporting view", fill="#1d4ed8", font=FONT_H)
    draw.text((640, 102), "Targeted re-observation view", fill="#b45309", font=FONT_H)
    draw.text((1240, 102), "Before crop", fill="#1d4ed8", font=FONT_H)
    draw.text((1510, 102), "Reobserve crop", fill="#b45309", font=FONT_H)

    before = (
        f"Views: {row['before_uav_ids']} ({row['before_view_count']})\n"
        f"Tokens: {row['before_token_count']}\n"
        f"Mean confidence: {float(row['before_mean_confidence']):.3f}\n"
        f"A(o): {float(row['before_ambiguity']):.3f}\n"
        f"Action: {row['before_action']}"
    )
    target = (
        f"Requested missing UAV(s): {row['missing_uav_ids']}\n"
        f"Selected UAV: {row.get('reobserve_uav_id') or 'none'}\n"
        f"Token: {row.get('reobserve_token_id') or 'no matching token'}\n"
        f"Confidence: {float(row.get('reobserve_confidence') or 0.0):.3f}\n"
        f"Match distance: {row.get('reobserve_match_distance', '-')}"
    )
    after = (
        f"Views: {row['after_uav_ids']} ({row['after_view_count']})\n"
        f"Raw A(o): {float(row['after_raw_ambiguity']):.3f}\n"
        f"Closed-loop A(o): {float(row['after_closed_loop_ambiguity']):.3f}\n"
        f"Action: {row['after_action']}\n"
        f"Outcome: {row['resolution_status']}"
    )
    draw_card(draw, (40, 500, 580, 830), "Before Graph State", before, "#2563eb")
    draw_card(draw, (630, 500, 1170, 830), "Targeted Evidence", target, "#f97316")
    draw_card(draw, (1220, 500, 1760, 830), "After Graph Update", after, "#16a34a" if row["resolved"] else "#64748b")
    note = (
        "Protocol: the before state is the 78-token viewer160 evidence graph. "
        "The re-observation token is selected from real-Cesium evidence in the missing UAV "
        "direction. When source metadata is targeted_reobservation, camera poses were "
        "commanded from the graph plan; this is still camera-pose closed-loop validation, "
        "not autonomous physical flight."
    )
    wrap(draw, note, (44, 880), 145, 26, fill="#334155")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path)


def build_contact_sheet(panel_paths: list[Path], out_path: Path) -> None:
    cols = 3
    thumb = (520, 324)
    rows = math.ceil(len(panel_paths) / cols)
    canvas = Image.new("RGB", (cols * 560 + 80, rows * 380 + 120), "#f8fafc")
    draw = ImageDraw.Draw(canvas)
    draw.rectangle([0, 0, canvas.width, 80], fill="#0f172a")
    draw.text((30, 22), "MarineCity Closed-loop Re-observation Panels", fill="white", font=FONT_TITLE)
    for idx, path in enumerate(panel_paths):
        x = 40 + (idx % cols) * 560
        y = 110 + (idx // cols) * 380
        draw.rounded_rectangle([x, y, x + 530, y + 350], radius=8, fill="#ffffff", outline="#cbd5e1", width=2)
        image = fit_image(path, thumb)
        canvas.paste(image, (x + 5, y + 8))
        draw.text((x + 14, y + 330), path.stem, fill="#334155", font=FONT_SMALL)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(out_path)


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fields = [
        "hypothesis_id",
        "scenario_short",
        "class_name",
        "before_view_count",
        "before_uav_ids",
        "missing_uav_ids",
        "before_token_count",
        "before_mean_confidence",
        "before_ambiguity",
        "before_action",
        "reobserve_uav_id",
        "reobserve_token_id",
        "reobserve_confidence",
        "reobserve_uncertainty",
        "reobserve_match_distance",
        "after_view_count",
        "after_uav_ids",
        "after_token_count",
        "after_mean_confidence",
        "after_raw_ambiguity",
        "after_closed_loop_ambiguity",
        "after_action",
        "resolved",
        "resolution_status",
        "panel_path",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def build_figures(out_dir: Path, rows: list[dict[str, Any]], summary: dict[str, Any]) -> None:
    fig_dir = out_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    labels = [row["hypothesis_id"] for row in rows]
    before = [float(row["before_ambiguity"]) for row in rows]
    raw_after = [float(row["after_raw_ambiguity"]) for row in rows]
    loop_after = [float(row["after_closed_loop_ambiguity"]) for row in rows]

    x = list(range(len(rows)))
    fig, ax = plt.subplots(figsize=(11, 4.8), dpi=180)
    ax.bar([i - 0.24 for i in x], before, width=0.22, label="Before A(o)", color="#2563eb")
    ax.bar(x, raw_after, width=0.22, label="After raw A(o)", color="#94a3b8")
    ax.bar([i + 0.24 for i in x], loop_after, width=0.22, label="After closed-loop A(o)", color="#16a34a")
    ax.axhline(0.75, color="#f97316", linestyle="--", linewidth=1.2, label="reobserve threshold")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=35, ha="right")
    ax.set_ylim(0.0, 1.05)
    ax.set_ylabel("ambiguity score")
    ax.set_title("Closed-loop targeted re-observation reduces routed hypothesis ambiguity")
    ax.grid(axis="y", color="#e2e8f0")
    ax.legend(ncol=2, fontsize=8)
    fig.tight_layout()
    fig.savefig(fig_dir / "closed_loop_ambiguity_before_after.png", facecolor="white")
    plt.close(fig)

    before_counts = Counter(row["before_action"] for row in rows)
    after_counts = Counter(row["after_action"] for row in rows)
    actions = ["finalize", "monitor", "reject", "targeted_reobserve"]
    fig, ax = plt.subplots(figsize=(7.8, 4.4), dpi=180)
    width = 0.36
    ax.bar([i - width / 2 for i in range(len(actions))], [before_counts.get(a, 0) for a in actions], width=width, label="Before", color="#2563eb")
    ax.bar([i + width / 2 for i in range(len(actions))], [after_counts.get(a, 0) for a in actions], width=width, label="After", color="#16a34a")
    ax.set_xticks(range(len(actions)))
    ax.set_xticklabels([a.replace("_", "\n") for a in actions])
    ax.set_ylabel("hypothesis count")
    ax.set_title("Action distribution before vs. after re-observation")
    ax.legend()
    ax.grid(axis="y", color="#e2e8f0")
    fig.tight_layout()
    fig.savefig(fig_dir / "closed_loop_action_distribution.png", facecolor="white")
    plt.close(fig)

    scenario_counts: dict[str, Counter[str]] = defaultdict(Counter)
    for row in rows:
        scenario_counts[row["scenario_short"]][row["resolution_status"]] += 1
    statuses = sorted({status for counts in scenario_counts.values() for status in counts})
    scenarios = sorted(scenario_counts)
    fig, ax = plt.subplots(figsize=(8.2, 4.4), dpi=180)
    bottom = [0] * len(scenarios)
    palette = ["#16a34a", "#f97316", "#64748b", "#dc2626"]
    for idx, status in enumerate(statuses):
        values = [scenario_counts[scenario].get(status, 0) for scenario in scenarios]
        ax.bar(scenarios, values, bottom=bottom, label=status.replace("_", " "), color=palette[idx % len(palette)])
        bottom = [bottom[i] + values[i] for i in range(len(values))]
    ax.set_ylabel("hypothesis count")
    ax.set_title("Closed-loop outcomes by MarineCity scenario")
    ax.legend(fontsize=7)
    ax.grid(axis="y", color="#e2e8f0")
    fig.tight_layout()
    fig.savefig(fig_dir / "closed_loop_outcomes_by_scenario.png", facecolor="white")
    plt.close(fig)

    scenario_summary: dict[str, Counter[str]] = defaultdict(Counter)
    for row in rows:
        scenario_summary[row["scenario_short"]]["routed"] += 1
        if row.get("reobserve_token_id"):
            scenario_summary[row["scenario_short"]]["matched"] += 1
        if row["resolved"]:
            scenario_summary[row["scenario_short"]]["resolved"] += 1

    fig, axes = plt.subplots(1, 3, figsize=(14, 4.5), dpi=220)
    fig.suptitle("MarineCity Closed-loop Targeted Re-observation Summary", fontsize=16, fontweight="bold", y=1.03)

    ax = axes[0]
    vals = [summary["mean_before_ambiguity"], summary["mean_after_closed_loop_ambiguity"]]
    bars = ax.bar(["Before", "After"], vals, color=["#2563eb", "#16a34a"], width=0.55)
    ax.axhline(0.75, color="#f97316", linestyle="--", linewidth=1.4, label="reobserve threshold")
    ax.set_ylim(0, 1.05)
    ax.set_ylabel("mean ambiguity")
    ax.set_title("Ambiguity Drops")
    ax.grid(axis="y", color="#e2e8f0")
    for bar, value in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width() / 2, value + 0.025, f"{value:.3f}", ha="center", fontsize=11, fontweight="bold")
    ax.legend(loc="lower left", fontsize=8, frameon=False)

    ax = axes[1]
    before_reobs = summary["before_action_counts"].get("targeted_reobserve", 0)
    after_monitor = summary["after_action_counts"].get("monitor", 0)
    after_reobs = summary["after_action_counts"].get("targeted_reobserve", 0)
    ax.bar(["Before"], [before_reobs], color="#2563eb", width=0.55, label="targeted reobserve")
    ax.bar(["After"], [after_monitor], color="#16a34a", width=0.55, label="monitor")
    ax.bar(["After"], [after_reobs], bottom=[after_monitor], color="#f97316", width=0.55, label="still reobserve")
    ax.set_ylim(0, max(1, before_reobs) + 1)
    ax.set_ylabel("hypotheses")
    ax.set_title("Action Transition")
    ax.grid(axis="y", color="#e2e8f0")
    ax.text(0, before_reobs + 0.25, f"{before_reobs}", ha="center", fontsize=11, fontweight="bold")
    ax.text(1, after_monitor / 2, f"{after_monitor} monitor", ha="center", color="white", fontsize=10, fontweight="bold")
    if after_reobs:
        ax.text(1, after_monitor + after_reobs / 2, f"{after_reobs} remain", ha="center", color="white", fontsize=10, fontweight="bold")
    ax.legend(loc="upper right", fontsize=8, frameon=False)

    ax = axes[2]
    scenarios = sorted(scenario_summary)
    xs = list(range(len(scenarios)))
    matched = [scenario_summary[item]["matched"] for item in scenarios]
    resolved = [scenario_summary[item]["resolved"] for item in scenarios]
    ax.bar([x - 0.18 for x in xs], matched, width=0.32, color="#0ea5e9", label="matched")
    ax.bar([x + 0.18 for x in xs], resolved, width=0.32, color="#16a34a", label="resolved")
    ax.set_xticks(xs)
    ax.set_xticklabels(scenarios)
    ax.set_ylim(0, max(3, max(matched + resolved, default=0)) + 0.7)
    ax.set_ylabel("hypotheses")
    ax.set_title("Per-scenario Closure")
    ax.grid(axis="y", color="#e2e8f0")
    for x, value in zip([x - 0.18 for x in xs], matched):
        ax.text(x, value + 0.08, str(value), ha="center", fontsize=10, fontweight="bold")
    for x, value in zip([x + 0.18 for x in xs], resolved):
        ax.text(x, value + 0.08, str(value), ha="center", fontsize=10, fontweight="bold")
    ax.legend(loc="upper left", fontsize=8, frameon=False)

    fig.text(
        0.5,
        -0.02,
        "Fresh commanded Isaac/Cesium camera-pose recapture; validates evidence update, not autonomous physical UAV flight.",
        ha="center",
        fontsize=10,
        color="#475569",
    )
    fig.tight_layout()
    fig.savefig(fig_dir / "closed_loop_summary_card.png", facecolor="white", bbox_inches="tight")
    plt.close(fig)

    write_json(fig_dir / "figure_manifest.json", {
        "summary_card": str(fig_dir / "closed_loop_summary_card.png"),
        "ambiguity": str(fig_dir / "closed_loop_ambiguity_before_after.png"),
        "action_distribution": str(fig_dir / "closed_loop_action_distribution.png"),
        "outcomes_by_scenario": str(fig_dir / "closed_loop_outcomes_by_scenario.png"),
        "summary": summary,
    })


def write_markdown(out_dir: Path, rows: list[dict[str, Any]], summary: dict[str, Any]) -> None:
    protocol_title = summary["evidence_protocol_label"]
    lines = [
        "# MarineCity Closed-loop Re-observation Evidence Update",
        "",
        "This package is a review-response artifact. It does not edit the paper tree.",
        "",
        "## Protocol",
        "",
        "- Before state: 78-token viewer160 real-Cesium evidence graph.",
        "- Routed set: hypotheses whose graph action is `targeted_reobserve`.",
        f"- Re-observation evidence: {protocol_title}, matched to the missing UAV direction, scenario, and class.",
        "- Graph update: insert the matched EvidenceToken into the hypothesis and recompute the closed-loop action.",
        f"- Scope: {summary['claim_boundary']}",
        "",
        "## Summary",
        "",
        f"- Routed hypotheses: `{summary['routed_hypotheses']}`",
        f"- Matched re-observation tokens: `{summary['matched_reobservation_tokens']}`",
        f"- Resolved from re-observe to monitor/finalize/reject: `{summary['resolved_hypotheses']}`",
        f"- Mean A(o) before: `{summary['mean_before_ambiguity']:.3f}`",
        f"- Mean raw A(o) after token insertion: `{summary['mean_after_raw_ambiguity']:.3f}`",
        f"- Mean closed-loop A(o) after missing-evidence completion: `{summary['mean_after_closed_loop_ambiguity']:.3f}`",
        f"- Before action counts: `{summary['before_action_counts']}`",
        f"- After action counts: `{summary['after_action_counts']}`",
        "",
        "## Generated Figures",
        "",
        "- `figures/closed_loop_ambiguity_before_after.png`",
        "- `figures/closed_loop_summary_card.png`",
        "- `figures/closed_loop_action_distribution.png`",
        "- `figures/closed_loop_outcomes_by_scenario.png`",
        "- `closed_loop_contact_sheet.png`",
        "",
        "## Paper-strengthening Text Candidates",
        "",
        "1. Add a short subsection titled `Closed-loop re-observation evidence update` after the MarineCity routing result.",
        f"2. State that the original graph routes {summary['routed_hypotheses']} ambiguous hypotheses to targeted re-observation, and the {protocol_title} provides matching evidence for {summary['matched_reobservation_tokens']} of them.",
        "3. Report the before/after trend: the matched subset moves from targeted re-observation to monitor under the closed-loop score, reducing mean ambiguity over routed cases.",
        f"4. Be careful with claim scope: {summary['claim_boundary']}",
        "5. Use unresolved cases as honest failure cases: missing-view recapture did not always produce a same-class token, so the policy keeps those hypotheses under re-observation.",
        "",
        "## Per-hypothesis Table",
        "",
        "| Hyp. | Scenario | Class | Before views | Missing UAV | Before A | Reobs token | After views | After A(loop) | After action | Outcome |",
        "|---|---|---|---:|---|---:|---|---:|---:|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| {row['hypothesis_id']} | {row['scenario_short']} | {row['class_name']} | "
            f"{row['before_view_count']} | {row['missing_uav_ids']} | {float(row['before_ambiguity']):.3f} | "
            f"{row.get('reobserve_token_id') or '-'} | {row['after_view_count']} | "
            f"{float(row['after_closed_loop_ambiguity']):.3f} | {row['after_action']} | {row['resolution_status']} |"
        )
    (out_dir / "closed_loop_reobservation_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def build_rows(args: argparse.Namespace) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    hypotheses = read_json(args.base_graph / "hypotheses.json")
    base_tokens = load_base_tokens(args.base_graph)
    reobs_tokens = load_tokens_jsonl(args.reobserve_tokens)
    fresh_commanded = any(
        str(token.metadata.get("source", "")).endswith("targeted_reobservation")
        or "targeted_reobservation" in str(token.metadata.get("image_path", ""))
        for token in reobs_tokens
    )
    if fresh_commanded:
        evidence_protocol = "fresh_commanded_isaac_cesium_targeted_reobservation"
        evidence_protocol_label = "fresh commanded Isaac/Cesium targeted camera-pose recapture"
        claim_boundary = (
            "Fresh camera poses are generated from the graph target plan and recaptured in Isaac/Cesium; "
            "this supports closed-loop camera-pose/evidence-update validation, not autonomous physical drone flight."
        )
    else:
        evidence_protocol = "saved_real_cesium_session_recapture_replay"
        evidence_protocol_label = "saved real-Cesium session-recapture detector tokens"
        claim_boundary = (
            "Closed-loop replay using saved real-Cesium recapture tokens; "
            "do not claim fully autonomous physical re-observation from this artifact alone."
        )
    reobs_projections = {token.token_id: token_projection(token, args.hfov_deg, args.ground_z) for token in reobs_tokens}

    rows: list[dict[str, Any]] = []
    panel_paths: list[Path] = []
    for hypothesis in hypotheses:
        if hypothesis.get("recommended_action") != "targeted_reobserve":
            continue
        token, match_distance, considered = find_reobserve_candidate(
            hypothesis,
            reobs_tokens,
            reobs_projections,
            max_distance=args.max_match_distance,
            min_confidence=args.min_reobserve_confidence,
        )
        after = after_state(
            hypothesis,
            token,
            support_gain=args.support_gain,
            confidence_gain_weight=args.confidence_gain_weight,
            max_confidence_gain=args.max_confidence_gain,
        )
        base_token = base_tokens.get((hypothesis.get("token_ids") or [""])[0])
        panel_path = args.out_dir / "panels" / f"{hypothesis['hypothesis_id']}_closed_loop.png"
        row = {
            "hypothesis_id": hypothesis["hypothesis_id"],
            "scenario_short": hypothesis["scenario_short"],
            "class_name": hypothesis["class_name"],
            "before_view_count": int(hypothesis["view_count"]),
            "before_uav_ids": ",".join(hypothesis.get("uav_ids", [])),
            "missing_uav_ids": ",".join(hypothesis.get("missing_uav_ids", [])),
            "before_token_count": int(hypothesis.get("token_count", 0)),
            "before_mean_confidence": float(hypothesis.get("mean_confidence", 0.0)),
            "before_ambiguity": float(hypothesis.get("ambiguity_score", 0.0)),
            "before_action": hypothesis.get("recommended_action", ""),
            "reobserve_uav_id": token.uav_id if token else "",
            "reobserve_token_id": token.token_id if token else "",
            "reobserve_confidence": float(token.confidence) if token else "",
            "reobserve_uncertainty": float(token.uncertainty) if token else "",
            "reobserve_match_distance": f"{match_distance:.2f}" if match_distance is not None else "",
            "candidate_count": len(considered),
            "candidate_tokens": considered,
            "panel_path": str(panel_path),
            **after,
        }
        row["after_uav_ids"] = ",".join(row["after_uav_ids"])
        build_panel(row, base_token, token, panel_path)
        panel_paths.append(panel_path)
        rows.append(row)

    summary = {
        "status": "closed_loop_reobservation_update_complete",
        "evidence_protocol": evidence_protocol,
        "evidence_protocol_label": evidence_protocol_label,
        "base_graph": str(args.base_graph),
        "reobserve_tokens": str(args.reobserve_tokens),
        "output_dir": str(args.out_dir),
        "routed_hypotheses": len(rows),
        "matched_reobservation_tokens": sum(1 for row in rows if row.get("reobserve_token_id")),
        "resolved_hypotheses": sum(1 for row in rows if row["resolved"]),
        "mean_before_ambiguity": sum(float(row["before_ambiguity"]) for row in rows) / max(1, len(rows)),
        "mean_after_raw_ambiguity": sum(float(row["after_raw_ambiguity"]) for row in rows) / max(1, len(rows)),
        "mean_after_closed_loop_ambiguity": sum(float(row["after_closed_loop_ambiguity"]) for row in rows) / max(1, len(rows)),
        "before_action_counts": dict(Counter(row["before_action"] for row in rows)),
        "after_action_counts": dict(Counter(row["after_action"] for row in rows)),
        "support_gain": args.support_gain,
        "confidence_gain_weight": args.confidence_gain_weight,
        "max_confidence_gain": args.max_confidence_gain,
        "max_match_distance": args.max_match_distance,
        "min_reobserve_confidence": args.min_reobserve_confidence,
        "claim_boundary": claim_boundary,
        "panel_count": len(panel_paths),
        "contact_sheet": str(args.out_dir / "closed_loop_contact_sheet.png"),
    }
    build_contact_sheet(panel_paths, args.out_dir / "closed_loop_contact_sheet.png")
    return rows, summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Build MarineCity closed-loop re-observation update artifacts.")
    parser.add_argument("--base-graph", type=Path, default=DEFAULT_BASE_GRAPH)
    parser.add_argument("--reobserve-tokens", type=Path, default=DEFAULT_REOBS_TOKENS)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--hfov-deg", type=float, default=60.0)
    parser.add_argument("--ground-z", type=float, default=0.0)
    parser.add_argument("--max-match-distance", type=float, default=180.0)
    parser.add_argument("--min-reobserve-confidence", type=float, default=0.0)
    parser.add_argument("--support-gain", type=float, default=0.18)
    parser.add_argument("--confidence-gain-weight", type=float, default=0.08)
    parser.add_argument("--max-confidence-gain", type=float, default=0.04)
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    rows, summary = build_rows(args)
    write_csv(args.out_dir / "closed_loop_reobservation_results.csv", rows)
    write_json(args.out_dir / "closed_loop_reobservation_summary.json", summary)
    write_json(args.out_dir / "closed_loop_reobservation_rows.json", rows)
    build_figures(args.out_dir, rows, summary)
    write_markdown(args.out_dir, rows, summary)
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
